# Generated by Django 4.2 on 2023-04-27 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_task_duration_task_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, choices=[('UN', 'Unassign'), ('PR', 'In progress'), ('CO', 'Completed')], default='Un', max_length=2, null=True),
        ),
    ]
