# Generated by Django 4.2 on 2023-05-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_created_by_alter_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='response',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('P', 'Rejected'), ('A', 'Accepted')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, choices=[('UN', 'Unassign'), ('PR', 'In progress'), ('CO', 'Completed')], default='UN', max_length=2, null=True),
        ),
    ]
